# Generated by Django 2.2.7 on 2020-07-25 22:37

import archive_ESTM.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ESTM_archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('mol2_file', models.FileField(upload_to=archive_ESTM.models.user_directory_path)),
                ('xyz_file', models.FileField(upload_to=archive_ESTM.models.user_directory_path)),
                ('charge', models.IntegerField(default=0)),
                ('multiplicity', models.IntegerField(default=1)),
                ('basis_set', models.CharField(max_length=50)),
                ('num_states', models.IntegerField(default=6)),
                ('selected_state', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='estm_archive',
            constraint=models.UniqueConstraint(fields=('owner', 'project_name'), name='same_project_name_arch'),
        ),
    ]
