# Generated by Django 2.2.7 on 2020-06-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESTM_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('xyz_file', models.FileField(upload_to='xyzfiles/')),
                ('charge', models.IntegerField(default=0)),
                ('multiplicity', models.IntegerField(default=1)),
                ('basis_set', models.CharField(choices=[('STO-3G', 'STO-3G'), ('3-21G', '3-21G'), ('6-31G', '6-31G'), ('6-31+G*', '6-31+G*'), ('6-31++G**', '6-31++G**'), ('6-311G', '6-311G'), ('6-311+G*', '6-311+G*'), ('6-311++G**', '6-311++G**'), ('cc-pVDZ', 'cc-pVDZ'), ('cc-pVTZ', 'cc-pVTZ'), ('aug-cc-pVDZ', 'aug-cc-pVDZ'), ('aug-cc-pVTZ', 'aug-cc-pVTZ')], default='STO-3G', max_length=11)),
                ('num_states', models.IntegerField(default=6)),
                ('selected_state', models.IntegerField(default=1)),
            ],
        ),
    ]
