# Generated by Django 2.2.7 on 2020-07-25 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GRANT_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ESTM_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('xyz_file', models.FileField(upload_to='xyzfiles/')),
                ('charge', models.IntegerField(default=0)),
                ('multiplicity', models.IntegerField(default=1)),
                ('basis_set', models.CharField(choices=[('STO-3G', 'STO-3G'), ('3-21G', '3-21G'), ('6-31G', '6-31G'), ('6-31+G*', '6-31+G*'), ('6-31++G**', '6-31++G**'), ('6-311G', '6-311G'), ('6-311+G*', '6-311+G*'), ('6-311++G**', '6-311++G**'), ('cc-pVDZ', 'cc-pVDZ'), ('cc-pVTZ', 'cc-pVTZ'), ('aug-cc-pVDZ', 'aug-cc-pVDZ'), ('aug-cc-pVTZ', 'aug-cc-pVTZ')], default='STO-3G', max_length=11)),
                ('num_states', models.IntegerField(default=6)),
                ('selected_state', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='estm_object',
            constraint=models.UniqueConstraint(fields=('owner', 'project_name'), name='same_project_name'),
        ),
    ]
