# Generated by Django 2.2.7 on 2020-07-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTM', '0003_grant_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant_object',
            name='email',
        ),
        migrations.AlterField(
            model_name='grant_object',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
